### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter.VisualStudio#27] opened 2018-01-09 15:53 UTC
Release a new version that includes a change required in Starcounter 2.4 (https://github.com/Starcounter/Starcounter.VisualStudio/pull/26)

Having that new version in Starcounter 2.3.1 is nice to have, but that's less important.

**Comment by ubbeK** [comment] 2018-01-09 16:39
@per-samuelsson What should we bump the version to? `2.0.0-RC2`

https://github.com/Starcounter/Starcounter.VisualStudio/blob/develop/build/version.txt

https://www.nuget.org/packages/Starcounter.VisualStudio/

**Comment by per-samuelsson** [comment] 2018-01-10 07:06
> @per-samuelsson What should we bump the version to? `2.0.0-RC2`

Not sure tbh. Maybe just 2.0.1 or something? There is currently no semantics at all in those numbers, except that we distinguish between version to be used in 2.4 and in all versions prior to that.

Also: we really must try to support only a single version of the extension, not multiple ones as today. The problem we are facing with that is projects should have different assembly referencing in 2.4 (with compile-time weaving and self-hosting) compared to previous versions.

**Comment by ubbeK** [comment] 2018-01-10 08:54
> Also: we really must try to support only a single version of the extension, not multiple ones as today. 

This is something that we will discuss at next RP meeting as it concerns multiple packages.

**Comment by ubbeK** [comment] 2018-01-10 08:58
@iqbalskd 
 Could you please release a new nuget version of this of develop branch. 
* Follow the instructions in https://github.com/Starcounter/Starcounter.VisualStudio#pushing-to-nugetorg
* The version should be `2.0.1`
* Create a git tag as well
* ask me for the nuget api key, `%StarcounterNuGetKeyFull%`

**Comment by iqbalskd** [comment] 2018-01-10 19:23
Published a new release and pushed the nuget package.

**Comment by warpech** [comment] 2018-01-11 15:57
In my Visual Studio 2017 I still have the version `1.0.3` of the extension. How do I upgrade that?

![2018-01-11 16_55_44-start page - microsoft visual studio](https://user-images.githubusercontent.com/566463/34833756-764e10be-f6f0-11e7-843b-a669ad679cfb.png)

Visual Studio Marketplace seems to not know about the current version: https://marketplace.visualstudio.com/items?itemName=Starcounter.StarcounterforVisualStudio

**Comment by per-samuelsson** [comment] 2018-01-11 17:02
> Visual Studio Marketplace seems to not know about the current version

That is correct. The marketplace can handle only a single version only 😞 😮 

You need to either build the 2.x extension yourself, or grab it from a local Level1-build. I think I added some instruction at some point, I'll see if I can find it.

**Comment by per-samuelsson** [comment] 2018-01-11 17:03
>  I think I added some instruction at some point, I'll see if I can find it.

https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility#i-cant-find-version-2x-of-the-extension-on-the-visual-studio-marketplace

**Comment by warpech** [comment] 2018-01-11 21:59
Thanks for the explanation, I missed that because actually, the extension 1.0.3 seems to work with Starcoutner 2.4 to some extent. And 1.0.3 is still the version that is offered by the installer, isn't it?

I will continue in https://github.com/Starcounter/Starcounter.VisualStudio/issues/28

**Comment by per-samuelsson** [comment] 2018-01-12 07:28
> And 1.0.3 is still the version that is offered by the installer, isn't it?

It depends on the version of Starcounter you install. If you install 2.4, the version of the extension being installed will be `2.0.*.`.

**Comment by warpech** [comment] 2018-01-12 11:00
I did an upgrade from 2.3.1 and it did not offer upgrading the extension :(

**Comment by per-samuelsson** [comment] 2018-01-15 07:52
> I did an upgrade from 2.3.1 and it did not offer upgrading the extension :(

As far as I recall, that's by design. 

We had long discussions about how to support the Visual Studio extension, and its future. We've had so much maintenance of it in the past, and in particular during install/uninstall from our custom installer, so we decided to try to keep that down to a minimum.

One thing we decided there was that we'd offer just to install the extension as part of the install, offer no explicit upgrade and also never touch it during uninstall. Basically, given new developers the chance to get a jump start at it, but then maintenance of the extension and upgrading it is on them.

**Comment by warpech** [comment] 2018-01-15 12:38
> Basically, given new developers the chance to get a jump start at it, but then maintenance of the extension and upgrading it is on them.

Please note that Starcounter 2.4 is already used by 33% of all developers (internal and partners). In result of this policy, many people that use Starcounter 2.4 have the wrong version of the extension.

I made a survey and it turns out that all people in the Apps Team have the correct version of the extension but most people in the Web Platform Team have a wrong version:

![image](https://user-images.githubusercontent.com/566463/34942762-1be26c90-f9f9-11e7-850a-2599ba4c716a.png)

![image](https://user-images.githubusercontent.com/566463/34942780-2acadac6-f9f9-11e7-866c-4e379d74fd49.png)

I have asked the Web Platform Team to upgrade the extension.

Is it possible that we make a warning in the extension that says "The version of Starcounter for Visual Studio (1.0.3) is incompatible with the installed version of Starcounter (2.4.0.4412)."

**Comment by warpech** [comment] 2018-01-15 12:50
BTW. When uninstalling the extension and then installing `Starcounter.VS.vsix`, I get Starcounter for Visual Studio 2.0.0, which does not include https://github.com/Starcounter/Starcounter.VisualStudio/issues/25. 

Please release the extension 2.0.1 in a way that is installable by `Starcounter.VS.vsix`.

**Comment by ubbeK** [comment] 2018-01-15 12:57
> Please release the extension 2.0.1 in a way that is installable by Starcounter.VS.vsix.

Is that done through: https://marketplace.visualstudio.com/ ?

**Comment by warpech** [comment] 2018-01-21 22:27
Was that a question for me? If yes, then sorry, I don't know...

All I know is that 2.0.0 is still the version that I get from `Starcounter.VS.vsix`:

![2018-01-21 23_26_34-extensions and updates](https://user-images.githubusercontent.com/566463/35199723-9376b24e-ff02-11e7-8c47-a6bee3cf76ff.png)

**Comment by ubbeK** [comment] 2018-01-22 09:57
@iqbalskd Please check up on this again

**Comment by ubbeK** [comment] 2018-01-22 16:04
@per-samuelsson 

Do you know where the credentials are for https://marketplace.visualstudio.com/

**Comment by per-samuelsson** [comment] 2018-01-22 16:26
@ubbeK 

Hang on, I need to think. I'll get back to you in person.

**Comment by chrhol** [comment] 2018-01-23 12:26
The changes in PR https://github.com/Starcounter/Starcounter.VisualStudio/pull/32 (and https://github.com/Starcounter/level1/pull/4465) will also require an updated version for 2.4 (or atleast the nuget used in InstallerEngine).

**Comment by iqbalskd** [comment] 2018-02-08 18:00
This is already done under another issue so this now obsolete, I am closing this issue now.

Reference issue:
https://github.com/Starcounter/AdminTrack/issues/440

**Closed as completed** 2018-02-08 18:00 UTC
